import { Icountry } from "../model/Icountry";





export const COUNTRIES_META_DATA : Icountry[]   = [
  { Country: 'Afghanistan', Currency: 'Afghani', 'ISO-4217 Codes': 'AFN' },
  { Country: 'Albania', Currency: 'Albanian Lek', 'ISO-4217 Codes': 'ALL' },
  { Country: 'Algeria', Currency: 'Algerian Dinar', 'ISO-4217 Codes': 'DZD' },
  { Country: 'Andorra', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'Angola', Currency: 'Kwanza', 'ISO-4217 Codes': 'AOA' },
  { Country: 'Argentina', Currency: 'Argentine Peso', 'ISO-4217 Codes': 'ARS' },
  { Country: 'Armenia', Currency: 'Armenian Dram', 'ISO-4217 Codes': 'AMD' },
  { Country: 'Australia', Currency: 'Australian Dollar', 'ISO-4217 Codes': 'AUD' },
  { Country: 'Austria', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'Azerbaijan', Currency: 'Azerbaijani Manat', 'ISO-4217 Codes': 'AZN' },
  { Country: 'Bahamas', Currency: 'Bahamian Dollar', 'ISO-4217 Codes': 'BSD' },
  { Country: 'Bahrain', Currency: 'Bahraini Dinar', 'ISO-4217 Codes': 'BHD' },
  { Country: 'Bangladesh', Currency: 'Taka', 'ISO-4217 Codes': 'BDT' },
  { Country: 'Belgium', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'Bhutan', Currency: 'Ngultrum', 'ISO-4217 Codes': 'BTN' },
  { Country: 'Brazil', Currency: 'Brazilian Real', 'ISO-4217 Codes': 'BRL' },
  { Country: 'Canada', Currency: 'Canadian Dollar', 'ISO-4217 Codes': 'CAD' },
  { Country: 'China', Currency: 'Yuan Renminbi', 'ISO-4217 Codes': 'CNY' },
  { Country: 'Denmark', Currency: 'Danish Krone', 'ISO-4217 Codes': 'DKK' },
  { Country: 'Egypt', Currency: 'Egyptian Pound', 'ISO-4217 Codes': 'EGP' },
  { Country: 'France', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'Germany', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'India', Currency: 'Indian Rupee', 'ISO-4217 Codes': 'INR' },
  { Country: 'Indonesia', Currency: 'Rupiah', 'ISO-4217 Codes': 'IDR' },
  { Country: 'Italy', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'Japan', Currency: 'Yen', 'ISO-4217 Codes': 'JPY' },
  { Country: 'Malaysia', Currency: 'Malaysian Ringgit', 'ISO-4217 Codes': 'MYR' },
  { Country: 'Mexico', Currency: 'Mexican Peso', 'ISO-4217 Codes': 'MXN' },
  { Country: 'Nepal', Currency: 'Nepalese Rupee', 'ISO-4217 Codes': 'NPR' },
  { Country: 'Netherlands', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'New Zealand', Currency: 'New Zealand Dollar', 'ISO-4217 Codes': 'NZD' },
  { Country: 'Pakistan', Currency: 'Pakistan Rupee', 'ISO-4217 Codes': 'PKR' },
  { Country: 'Russia', Currency: 'Russian Ruble', 'ISO-4217 Codes': 'RUB' },
  { Country: 'Saudi Arabia', Currency: 'Saudi Riyal', 'ISO-4217 Codes': 'SAR' },
  { Country: 'Singapore', Currency: 'Singapore Dollar', 'ISO-4217 Codes': 'SGD' },
  { Country: 'South Africa', Currency: 'Rand', 'ISO-4217 Codes': 'ZAR' },
  { Country: 'South Korea', Currency: 'Won', 'ISO-4217 Codes': 'KRW' },
  { Country: 'Spain', Currency: 'Euro', 'ISO-4217 Codes': 'EUR' },
  { Country: 'Sri Lanka', Currency: 'Sri Lanka Rupee', 'ISO-4217 Codes': 'LKR' },
  { Country: 'Sweden', Currency: 'Swedish Krona', 'ISO-4217 Codes': 'SEK' },
  { Country: 'Switzerland', Currency: 'Swiss Franc', 'ISO-4217 Codes': 'CHF' },
  { Country: 'Thailand', Currency: 'Baht', 'ISO-4217 Codes': 'THB' },
  { Country: 'Turkey', Currency: 'Turkish Lira', 'ISO-4217 Codes': 'TRY' },
  { Country: 'Ukraine', Currency: 'Hryvnia', 'ISO-4217 Codes': 'UAH' },
  { Country: 'United Arab Emirates', Currency: 'UAE Dirham', 'ISO-4217 Codes': 'AED' },
  { Country: 'United Kingdom', Currency: 'Pound Sterling', 'ISO-4217 Codes': 'GBP' },
  { Country: 'United States', Currency: 'US Dollar', 'ISO-4217 Codes': 'USD' },
  { Country: 'Vietnam', Currency: 'Dong', 'ISO-4217 Codes': 'VND' }
];